SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 120
TITLE = "Cave Flyer"

SHIP_THRUST = 260.0
SHIP_ROTATION_SPEED = 200.0   # degrees per second
SHIP_RADIUS = 14
SHIP_DAMPING = 0.995          # slight damping to make control easier
BULLET_SPEED = 420.0
BULLET_RANGE = 520.0
BULLETS_DESTROY_SHIP = False
SHIP_BOUNCES_INSTEAD_OF_DYING = True
TURRET_BULLET_SPEED = 300.0
TURRET_FIRE_COOLDOWN = 1.8
TURRET_ACCURATE_CHANCE = 0.2
TURRET_INACCURATE_SPREAD_MIN = 10.0
TURRET_INACCURATE_SPREAD_MAX = 22.0
TANK_AIM_SPREAD_MIN = 12.0
TANK_AIM_SPREAD_MAX = 24.0
ORBIT_SCROLL_SPACE = 280.0
ORBIT_ESCAPE_MARGIN = 36.0

SHIP_MAX_FUEL = 800.0
SHIP_START_FUEL = 280.0
FUEL_POD_AMOUNT = 250.0
REACTOR_ESCAPE_TIME = 20.0

SHIP_NOSE_LEN_MULT = 1.45
SHIP_BASE_BACK_MULT = 0.80
SHIP_BASE_HALF_MULT = 1.05
BULLET_SPAWN_OFFSET = 6.0

TRACTOR_BEAM_LENGTH = 270.0
TRACTOR_BEAM_HALF_WIDTH = 54.0
TRACTOR_PULL_SPEED = 110.0
TRACTOR_TARGET_OFFSET = 10.0

ORB_PULSE_DURATION = 1.25
ORB_PULSE_FAST_RATE = 4.0
ORB_PULSE_SLOW_RATE = 1.3
ORB_FALL_MAX_SPEED = 260.0
ORB_FALL_DAMPING = 0.985

THRUST_PARTICLES_PER_FRAME = 8
THRUST_SPREAD_DEGREES = 12.0
THRUST_SPEED_MIN = 320.0
THRUST_SPEED_MAX = 430.0
THRUST_PARTICLE_LIFE = 0.32

TURRET_HIT_POINTS = 3
TURRET_RADIUS = 14
TURRET_EXPLOSION_PARTICLES = 44
TURRET_SPARK_SPEED_MIN = 90.0
TURRET_SPARK_SPEED_MAX = 280.0
TURRET_SPARK_LIFE_MIN = 0.25
TURRET_SPARK_LIFE_MAX = 0.55

TANK_RADIUS = 22
TANK_HALF_WIDTH = 28
TANK_HALF_HEIGHT = 16
TANK_SPEED = 42.0
TANK_FIRE_RANGE = 320.0
TANK_FIRE_COOLDOWN = 2.2
TANK_BULLET_SPEED = 260.0
TANKS_PER_LEVEL_MAX = 4

ROCK_GRAVITY_SCALE = 0.55
ROCK_AIR_DAMPING = 0.995
ROCK_GROUND_DAMPING = 0.62
ROCK_SLIDE_ACCEL = 42.0
ROCK_MAX_FALL_SPEED = 220.0
ROCK_TERRAIN_FRICTION = 0.72
ROCK_STOP_SPEED = 7.0
ROCK_PILE_MAX_COUNT = 28

FUEL_PARTICLE_VALUE = 8.0
FUEL_PARTICLE_SPAWN_INTERVAL = 0.055
FUEL_PARTICLE_PULL_SPEED = 175.0
FUEL_PARTICLE_FADE_TIME = 0.45

REACTOR_HIT_POINTS = 10
REACTOR_EXPLOSION_PARTICLES = 90
REACTOR_HIT_SPARKS = 14
REACTOR_DEBRIS_PARTICLES = 42

LEVEL_SELF_DESTRUCT_DURATION = 2.8
LEVEL_DESTRUCT_SPARK_BURST = 220
LEVEL_DESTRUCT_FLAME_BURST = 180
LEVEL_DESTRUCT_SPARKS_PER_FRAME = 10
LEVEL_DESTRUCT_FLAMES_PER_FRAME = 12

SHIP_DESTRUCTION_DURATION = 1.1
SHIP_DESTRUCTION_SPARKS = 30
SHIP_DESTRUCTION_FLAMES = 18
SHIP_DEBRIS_PARTICLES = 12

SHIP_BOUNCE_FLASH_DURATION = 0.32
SHIP_BOUNCE_RESTITUTION = 0.62


SHIP_TRANSPORTER_MATERIALIZE_DURATION = 0.6
SHIP_TRANSPORTER_DEMATERIALIZE_DURATION = 0.45
SHIP_TRANSPORTER_BEAM_WIDTH = 34
